FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app
EXPOSE 8080
ENV DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=1
CMD ["dotnet", "watch", "run", "--project", "LibraryPlus.csproj", "--urls", "http://0.0.0.0:8080"]