services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: some_secret_password
    command: mongod --quiet --logpath /dev/null 
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:some_secret_password@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      mongo:
        condition: service_healthy


  # dev build
  dotnet-app-dev:
    build:
      dockerfile: Dockerfile.dev
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - dotnet-bin:/app/bin
      - dotnet-obj:/app/obj
      - nuget-cache:/root/.nuget/packages

  # release build
  # dotnet-app:
  #   build: .
  #   depends_on:
  #     mongo:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"

volumes:
  db:
  # Only use the volumes below if you use the dotnet-app-dev
  nuget-cache:
  dotnet-bin:
  dotnet-obj:
